# Placeholder for Argo CD Helm chart values.
# Refer to the official chart documentation for available options:
# https://github.com/argo-proj/argo-helm/blob/main/charts/argo-cd/values.yaml

# Example: Configure ingress if needed
# server:
#   ingress:
#     enabled: true
#     ingressClassName: nginx
#     hosts:
#       - argocd.example.com
