apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
  - secretKey: client_id
    remoteRef:
      key: TAILSCALE_OAUTH_CLIENT_ID
  - secretKey: client_secret
    remoteRef:
      key: TAILSCALE_OAUTH_CLIENT_SECRET
