apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /charts/argo-cd
spec:
    project: default

    destination:
      server: https://kubernetes.default.svc
      namespace: argocd

    source:
      helm:
        valueFiles:
          - values.yaml
      path: charts/argo-cd
      repoURL: https://github.com/souzagab/lab.git
      targetRevision: main
  
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
