apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /
spec:
  project: default

  destination:
    name: ""
    server: https://kubernetes.default.svc
    namespace: argocd

  sources:
    - path: components
      repoURL: https://github.com/souzagab/lab
      targetRevision: main

    - path: apps
      repoURL: https://github.com/souzagab/lab
      targetRevision: main

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
