serviceMonitor:
  # -- Specifies whether to create a ServiceMonitor resource for collecting Prometheus metrics
  enabled: true

  # -- namespace where you want to install ServiceMonitors
  # namespace: monitoring

  # -- Additional labels
  additionalLabels:
    release: kube-prometheus-stack

  # --  Interval to scrape metrics
  interval: 30s

  # -- Timeout if metrics can't be retrieved in given time interval
  scrapeTimeout: 25s

  # -- Let prometheus add an exported_ prefix to conflicting labels
  honorLabels: false

  # -- Metric relabel configs to apply to samples before ingestion. [Metric Relabeling](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs)
  metricRelabelings: []
  # - action: replace
  #   regex: (.*)
  #   replacement: $1
  #   sourceLabels:
  #   - exported_namespace
  #   targetLabel: namespace

  # -- Relabel configs to apply to samples before ingestion. [Relabeling](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config)
  relabelings: []
  # - sourceLabels: [__meta_kubernetes_pod_node_name]
  #   separator: ;
  #   regex: ^(.*)$
  #   targetLabel: nodename
  #   replacement: $1
  #   action: replace

## -- Extra Kubernetes objects to deploy with the helm chart
extraObjects:
- apiVersion: external-secrets.io/v1beta1
  kind: ClusterSecretStore
  metadata:
    name: doppler
    namespace: external-secrets
  spec:
    provider:
      doppler:
        auth:
          secretRef:
            dopplerToken:
              name: doppler-token
              key: token
              namespace: external-secrets
