apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared

resources:
- resources/external-secret.yaml

patchesStrategicMerge:
- cloudflared-cm.yaml

helmGlobals:
  chartHome: charts
helmCharts:
- name: cloudflare-tunnel
  version: 0.3.0
  repo: https://cloudflare.github.io/helm-charts
  releaseName: cloudflare-tunnel
  valuesFile: values.yaml
