{{- if .Values.migrationsJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "nanami.fullname" . }}-migrations"
  labels:
    app.kubernetes.io/name: {{ include "nanami.name" . }}
    helm.sh/chart: {{ include "nanami.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  ttlSecondsAfterFinished: 30
  selector:
    matchLabels:
      job-name: "{{ include "nanami.fullname" . }}-migrations"
  template:
    metadata:
      labels:
        job-name: "{{ include "nanami.fullname" . }}-migrations"
        app.kubernetes.io/name: {{ include "nanami.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "nanami.serviceAccountName" . }}
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command: {{ toJson .Values.migrationsJob.command }}
          env:
            {{- range .Values.migrationsJob.env }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
            {{- end }}
          resources:
            {{- toYaml .Values.migrationsJob.resources | nindent 12 }}
      restartPolicy: {{ .Values.migrationsJob.restartPolicy }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 4
{{- end }}
