apiVersion: v1
kind: Service
metadata:
  name: {{ include "nanami.fullname" . }}
  labels:
    {{- include "nanami.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "nanami.selectorLabels" . | nindent 4 }}
