# Custom values for Chatwoot Helm chart

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: chatwoot.g0b.dev
  hosts:
    - host: chatwoot.g0b.dev
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: chatwoot
              port:
                number: 3000
  tls:
    - secretName: chatwoot-tls
      hosts:
        - chatwoot.g0b.dev

env:
  FRONTEND_URL: "https://chatwoot.g0b.dev"
  SECRET_KEY_BASE: "secret" # TODO: Move to ExternalSecret

postgresql:
  image:
    registry: docker.io
    repository: pgvector/pgvector
    tag: pg15

redis:
  image:
    registry: docker.io
    repository: arm64v8/redis
    tag: 6
