annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Set defaults for `automountServiceAccountToken` and `serviceAccount.automountServiceAccountToken` to `true` in Helm chart values."
    - kind: fixed
      description: "Correctly handles 'txtPrefix' and 'txtSuffix' arguments when both are provided."
    - kind: fixed
      description: "Add missing types in the schema for empty values."
apiVersion: v2
appVersion: 0.16.1
description: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with
  DNS providers.
home: https://github.com/kubernetes-sigs/external-dns/
icon: https://github.com/kubernetes-sigs/external-dns/raw/master/docs/img/external-dns.png
keywords:
- kubernetes
- externaldns
- external-dns
- dns
- service
- ingress
maintainers:
- email: steve.hipwell@gmail.com
  name: stevehipwell
name: external-dns
sources:
- https://github.com/kubernetes-sigs/external-dns/
type: application
version: 1.16.1
