## - Limit possible target zones by domain suffixes.
domainFilters:
  - g0b.dev

provider:
  # -- _ExternalDNS_ provider name; for the available providers and how to configure them see [README](https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/README.md#providers).
  name: cloudflare

## -- Extra Kubernetes objects to deploy with the helm chart
extraObjects:
  - apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: cloudflare-token
      namespace: external-dns
    spec:
      refreshInterval: "1800s"
      secretStoreRef:
        name: doppler
        kind: ClusterSecretStore
      target:
        name: cloudflare-token
        creationPolicy: Owner
      data:
        - secretKey: api-token
          remoteRef:
            key: CLOUDFLARE_KEY_VALUE