apiVersion: v2
appVersion: 5.6.24
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
- condition: nginx.enabled
  name: nginx
  repository: https://charts.bitnami.com/bitnami
  version: 13.x.x
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 11.4.x
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 16.x.x
description: A Helm chart to install Invoice Ninja
home: https://invoiceninja.github.io/dockerfiles
keywords:
- invoiceninja
maintainers:
- email: lwj5@hotmail.com
  name: lwj5
name: invoiceninja
sources:
- https://github.com/invoiceninja/invoiceninja
- https://github.com/invoiceninja/dockerfiles
type: application
version: 0.10.2
