apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: default

  source:
    repoURL: https://github.com/souzagab/lab
    targetRevision: HEAD
    path: charts/argo-cd
    helm:
      valueFiles:
        - config/argo-cd/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      # ignoreDifferences:
      # - group: apps
      #   kind: Deployment
      #   jsonPointers:
      #   - /spec/replicas 
