apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /charts/argo-cd
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - argocd.argoproj.io/resources-finalizer

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  source:
    repoURL: https://github.com/souzagab/lab
    targetRevision: main
    path: charts/argo-cd
    helm:
      valueFiles:
        - custom-values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      # ignoreDifferences:
      # - group: apps
      #   kind: Deployment
      #   jsonPointers:
      #   - /spec/replicas 
