apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: default

  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: "7.8.28"
      chart: argo-cd
      ref: chart
      helm:
        valueFiles:
          - $values/valuesRepo/config/argo-cd/values.yaml

    - repoURL: https://github.com/souzagab/lab
      targetRevision: HEAD 
      ref: valuesRepo

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      # ignoreDifferences:
      # - group: apps
      #   kind: Deployment
      #   jsonPointers:
      #   - /spec/replicas 
