apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
    argocd.argoproj.io/manifest-generate-paths: /charts/cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc

  source:
    repoURL: https://github.com/souzagab/lab
    targetRevision: main
    path: charts/cert-manager
    helm:
      valueFiles:
        - custom-values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
