apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /charts/external-secrets
spec:
    project: default

    destination:
      name: ""
      server: https://kubernetes.default.svc
      namespace: external-secrets

    source:
      helm:
        valueFiles:
          - values.yaml
      path: charts/external-secrets
      repoURL: https://github.com/souzagab/lab
      targetRevision: main
    
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
        allowEmpty: false
      syncOptions:
        - CreateNamespace=true
    