apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /charts/grafana
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    name: ""
    server: https://kubernetes.default.svc
    namespace: monitoring

  source:
    helm:
      valueFiles:
        - values.yaml
        - custom-values.yaml
    path: charts/grafana
    repoURL: https://github.com/souzagab/lab
    targetRevision: main

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
