apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /charts/ingress-nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
    project: default

    destination:
      name: ""
      server: https://kubernetes.default.svc
      namespace: ingress-nginx

    source:
      helm:
        valueFiles:
          - values.yaml
      path: charts/ingress-nginx
      repoURL: https://github.com/souzagab/lab
      targetRevision: main

    syncPolicy:
      automated:
        prune: true
        selfHeal: false
        allowEmpty: false
      syncOptions:
        - CreateNamespace=true
