apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /charts/ingress-nginx
    argocd.argoproj.io/sync-wave: "2"

spec:
    project: default

    destination:
      name: ""
      server: https://kubernetes.default.svc
      namespace: ingress-nginx

    source:
      helm:
        valueFiles:
          - values.yaml
      path: charts/ingress-nginx
      repoURL: https://github.com/souzagab/lab
      targetRevision: main

    syncPolicy:
      automated:
        prune: true
        selfHeal: true
        allowEmpty: false
      syncOptions:
        - CreateNamespace=true
