apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/manifest-generate-paths: /charts/longhorn
spec:
    project: default

    destination:
      name: ""
      server: https://kubernetes.default.svc
      namespace: longhorn

    source:
      helm:
        valueFiles:
          - values.yaml
          - custom-values.yaml
      path: charts/longhorn
      repoURL: https://github.com/souzagab/lab
      targetRevision: main

    syncPolicy:
      automated:
        prune: true
        selfHeal: true
        allowEmpty: false
      syncOptions:
        - CreateNamespace=true
