apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /charts/openebs
spec:
    project: default

    destination:
      name: ""
      server: https://kubernetes.default.svc
      namespace: openebs

    source:
      helm:
        valueFiles:
          - values.yaml
      path: charts/openebs
      repoURL: https://github.com/souzagab/lab
      targetRevision: main

    syncPolicy:
      automated:
        prune: true
        selfHeal: false
        allowEmpty: false
      syncOptions:
        - CreateNamespace=true
