apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /charts/rook-ceph

spec:
    project: default

    destination:
      name: ""
      server: https://kubernetes.default.svc
      namespace: rook-ceph

    source:
      helm:
        valueFiles:
          - values.yaml
          - custom-values.yaml
      path: charts/rook-ceph
      repoURL: https://github.com/souzagab/lab
      targetRevision: main

    syncPolicy:
      automated:
        prune: true
        selfHeal: false
        allowEmpty: false
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
