apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /charts/argo-cd
spec:
  generators:
    - git:
        repoURL: https://github.com/souzagab/lab.git
        revision: main
        directories:
          - path: apps/argo-cd
  template:
    metadata:
      name: argo-cd
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - values.yaml
        path: charts/argo-cd
        repoURL: https://github.com/souzagab/lab.git
        targetRevision: HEAD
  
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
          allowEmpty: false

