apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-cd
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/souzagab/lab.git
        revision: main
        directories:
          - path: apps/argo-cd
  template:
    metadata:
      name: argo-cd
    spec:
      project: default
      source:
        repoURL: https://github.com/souzagab/lab.git
        targetRevision: main
        path: charts/argo-cd
        chart: argo-cd
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
