apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
spec:
  generators:
  - git:
    repoURL: git@github.com:souzagab/lab.git
    revision: main
    directories:
      - path: apps/argo-cd
  template:
    metadata:
      name: argocd
    spec:
      project: default
      source:
        repoURL: https://argoproj.github.io/argo-helm
        targetRevision: 7.4.4
        chart: argo/argo-cd
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
