apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-apikey" (include "evolution-api.fullname" .) }}
  labels:
    {{- include "evolution-api.labels" . | nindent 4 }}
type: Opaque
data:
  # Default API key is 'secret', base64 encoded
  {{ .Values.evolutionApi.apiKeySecretKey }}: {{ "secret" | b64enc | quote }} 