# Placeholder for Argo CD Helm chart values.
# Refer to the official chart documentation for available options:
# https://github.com/argo-proj/argo-helm/blob/main/charts/argo-cd/values.yaml

# extraObjects:
#   - apiVersion: external-secrets.io/v1beta1
#     kind: ExternalSecret
#     metadata:
#       name: argocd
#       namespace: argocd
#     spec:
#       refreshInterval: "1800s"
#       secretStoreRef:
#         name: doppler
#         kind: ClusterSecretStore
#       target:
#         name: argocd-secret
#         creationPolicy: Merge
#       data:
#         - secretKey: admin.password
#           remoteRef:
#             key: ARGOCD_ADMIN_PASSWORD
