annotations:
  artifacthub.io/changes: |
    - Update cloudflare/cloudflared image version to 2025.4.0
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: cloudflared
      image: cloudflare/cloudflared:2025.4.0
      platforms:
        - linux/amd64
        - linux/arm64
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/community-charts/helm-charts
    - name: Upstream Project
      url: https://github.com/cloudflare/cloudflared
    - name: Official Documentation
      url: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/
  artifacthub.io/maintainers: |
    - name: burakince
      email: burak.ince@linux.org.tr
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/screenshots: |
    - title: Cloudflared Tunnel Overview
      url: https://raw.githubusercontent.com/cloudflare/cloudflare-docs/refs/heads/production/src/assets/images/cloudflare-one/connections/connect-apps/handshake.jpg
  artifacthub.io/signKey: |
    fingerprint: 939B1A0ED8AAA8E722ACCDB3B6A012EE8A76426A
    url: https://keybase.io/communitycharts/pgp_keys.asc
apiVersion: v2
appVersion: 2025.4.0
description: A Helm chart for cloudflare tunnel
home: https://github.com/cloudflare/cloudflared
icon: https://raw.githubusercontent.com/cloudflare/color/refs/heads/master/static/thinking/logo.png
keywords:
- kubernetes
- reverse-proxy
- cloudflare
- cloudflared
- argo-tunnel
- argo
- tunnel
- zero-trust-network-access
- cloudflare-tunnel
kubeVersion: '>=1.21.0-0'
maintainers:
- email: burak.ince@linux.org.tr
  name: burakince
  url: https://www.burakince.com
name: cloudflared
sources:
- https://github.com/community-charts/helm-charts
- https://github.com/cloudflare/cloudflared
type: application
version: 2.0.3
