apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatwoot
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /charts/chatwoot
  # finalizers:
  #   - argocd.argoproj.io/resources-finalizer

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: chatwoot

  source:
    repoURL: https://github.com/souzagab/lab
    targetRevision: main
    path: charts/chatwoot
    helm:
      valueFiles:
        - custom-values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
