apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale

resources:
- resources/external-secret.yaml

helmGlobals:
  chartHome: charts
helmCharts:
- name: tailscale-operator
  version: 1.62.0
  repo: https://pkgs.tailscale.com/helmchart
  releaseName: tailscale-operator
  valuesFile: values.yaml
